# Generated by Django 4.1.4 on 2022-12-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_auto_20221220_1217"),
    ]

    operations = [
        migrations.RenameModel(old_name="Articles", new_name="Article",),
    ]
